### PR TITLE
Add devDependencies: grunt-contrib-clean

### PR DESCRIPTION
**Pull request by hariadi**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Ha, I just fixed these at the same time. Sorry about that!

**Comment by jonschlinkert** [comment]
@hariadi, I completely refactored this again... I had to recreate the project since it was initially a fork and that was confusing. Now, you should be able to pull it down and run it fine. 

Let me know if it works for you.

**Comment by hariadi** [comment]
Lol! I just see on your timeline. No problem.

When `bower install`, .jshintrc missing. Is this file ignore from bower?

**Comment by jonschlinkert** [comment]
I mentioned this on the last issue before I deleted the repo. It's a jshint bug that was fixed. Make sure you are installing from a clean slate, and also do `npm cache clean` if that doesn't work. Just remember to do `npm i -g grunt-cli` afterwards.

**Comment by jonschlinkert** [comment]
actually, this issue could also be bower, so make sure to do `bower update`

**Comment by hariadi** [comment]
Alright, thanks. All working now!

**Comment by jonschlinkert** [comment]
Great! thanks

**Pull request closed without merging**
